package ubordeaux.deptinfo.compilation.project.main;

import java.util.Iterator;
import ubordeaux.deptinfo.compilation.project.type.*;
import fr.groupname.compilator.environment.*;
import java.util.Scanner;
import java.util.HashMap;
import java.util.Stack;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import ubordeaux.deptinfo.compilation.project.intermediateCode.*;
import java.util.Map;
import fr.groupname.compilator.error.*;
import beaver.*;
import fr.groupname.compilator.special.*;
import ubordeaux.deptinfo.compilation.project.node.*;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "Parser.grammar".
 */
public class Parser extends beaver.Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pjM0kOJLKK$i#vjzSKpQ1CcWn5CwY4eWQJDqFaFGOPXl6c52MbFA88UHL2H9gyASyIaXg" +
		"lKbBfhTBBewBtS$MVC#lEd7lkkTUCfhxFztNd#y#$zbfxht$jUyxPUzy1$5beYrZSXBheXX" +
		"9OWtDn7egWACv7D69G3CLn0Iv4ITJ3jRWUAQY1fcY66z4SyOX3UIJWB9Xo4AzhwnAKnMKOB" +
		"kFH2uFG2ktG0PtG1GCyCfpzZxLxKEaWVC7QE2CVsfaSjnVhSITMqTg8vpdEhtc6Osr81cUb" +
		"KGMgD1ajK1krK9Sw5xagFRCGTHfX8Xh8KJmj1sMdI#USY3fz2wHJIcSZd4#SIoSveax$0kc" +
		"Kpj51d8TE$OWwjnP0fuogF8jvrBaqeAdFmU28ElSKGAUSPfwBXjIvtANJCgBECs5ruh4GAx" +
		"0Coz66FJS4VKlnk1WLK0bNeZAge5fGB1dJWsBng8b4hIa3tLrvUeRDausEhZnRy2Bge6BG$" +
		"09vRWwR9nvT8yJwXO$9ks5ZjsD4KEm#z66kAxIo7TY4ErmwjqIeOMdOs1na1SL2x$r2ZC5a" +
		"JC4et8#nU00FOXokqZg6oiRS#0n7FE2RvU5xmiFtYeVlDG$VMmvVQAN$UqulpqJSRQtuk8l" +
		"MCDkQIIlBmyfMwsfzxcPYDz$KIPYAnp0U3s52lgs969chELgpLitDUerQrPMlKqvIVXZJFB" +
		"FUeF4coctHMhczpMdgxwoShjnRUQ3oRShhkBSFmGWvOE$jrYw$0IkHYgUmNLx3Tho3H$0ev" +
		"c4s7iTyt8i5U1AD#IQ$mNajmZPxVKZ64lbAzcAnx9KlvGkinWjuJlPXCyTlnKju6Jkn2szY" +
		"3rxbTH$UndxUdoIkfRLOHJBdL8ULrEDkrG0DkJytvknIx7jdmEIfnS#JofayFvtD$TdKtJu" +
		"DcLpZhmlQ#sEvCfNYQXx75QSqrw8oN7T2CrGg1ErOQjTsQKVdIpkQkrOwdwugjBhpN1RBNI" +
		"CdJopNRtU6KwyqCNTiDDVGu4ex5A9EVte7sjvemANJiH1r0YD1dIYNJkA$e1FbeUChD9t0k" +
		"0p6eXsQES$1W4BNkOOdwb2Tc5FKCUqrjGNFNJ5sJ#UtPEgvguIUl9onHAv2pfZ9glAUqWwk" +
		"F1t3vabrQPWy5NNZsI9uVYUl9tAiUeHOTDXODDTXP#ncxaLvJzKLFFrak7BLYA3JEMoi3##" +
		"sCnPwxmFtg2NFowrvxctBKtEWZlRyvhtY$uKljDB$FQUR9y7sLAHbs5PK62jLhRmtqtfJA$" +
		"FtusNyfLUUl#$oQparOqAo1gnmR73jySfwid45PMjlhyItAsTljtRvYxW2nF1gsEZ4LQegk" +
		"HhVx0JqjMTYpQWNh#q9Qtr8vDmgi7TbeWB$4kmPMpsj7AbsEyTEi3F6S7y73epWHKIEa1e3" +
		"vataDCl7po2Y674OCE8itwc0dmU9QipnGPxF$8ENue3l378hSb7oFUIIxCSklZBa4kGAv4R" +
		"ageoN8jSaTo0t82ydDoT$GcxFVXUGqyafvDxaDMJEmMX27aO#xAZfB$f6imv7dKOgsrdaUJ" +
		"bjVoVscK3VOEzvcQFOTtMExNk4zZxrJsRxSOxFr1XpcaNLNaMxdDeRQLTLxL#qhaL4opmDt" +
		"pRsgKFZNVB5x5T4$RlPRi5sNMtlPxip3Tu$Vpr7ZVCPsq1yfZf3jFzNn36rJn0VSbmHhtbw" +
		"pzstb$sh1$lyradk4BaDqOnzFjM#NshyHc8uQnZj6DEHyQFasxGzaXX3T77qoI36EzezYRv" +
		"4FsqFPCx5hbhIzVlih#snoWyGl5V#HuaxYL7gxqhCKliErdJSaMikCOUuY#2pxB#RAEc8po" +
		"CMg3sKY2EcE#lX#xM9L8w8rxfwqfTDvlmnCx$VUpZmyt5msoYkt4YvkV8mvP7AkvMFvx2Ph" +
		"ApVYs#pyjVAtoYVKFv9#RVGclnH7dKETVKfch$v#OkvsXSwx58EkxJ3lZHuZB6Q5skzcKHx" +
		"lVQvNElQfgppyLVKCSh#gxHTrdeFytAQVLmQNRH$B6EEPyJCpCyyJ$uz6DCSEVLTDkzp#6f" +
		"Gkrpm67DSSDjVxHHqfxfow3faP4KOa#qQqz1HqxJG$huvZlXSnxWoH8eZbXKy3WVuXlqb1o" +
		"rJTa0$aYqlotPvIRR9Yx9LjiXcUK5MoKfP8SjbYjrZaopWzGbYFi6tMBXg2zzqcKtC8cOIC" +
		"mYk5i9LGwOJN0taCNlyD9cgcHRAP7dIjfwph#lbOPaa4sM2F2JhsEjv#gR8MZisHTRO$Anz" +
		"VSQ#hWvKBZjbbzQ$Z5YgzfBSMIsMfzLwdtYA#5W#Kiy7ygly8Z$BJ$AZ$23VomavBj$HVrY" +
		"#bM#G#v6lYS$LFYIVgVM9yZ5vp#OZygbwFhIlYoHBNY6$Gxn5x9StSpE#OLzVjQ#xPGyS7t" +
		"bTtkRrJ$b3sx$9xwGXk8LdmanQcTo4UzcmJYL#dlaDJxHoe3dHMj62OxYpSEVpsMZ3ysPl#" +
		"WDeozpjsASFsVhrqvbsRVQlpNPV6mRFMdwUeto40UukX85#ZFKZTo5RIAVTdUZ1DQG7JxHT" +
		"sQyhszquhfkUMPEfRQteFA4WZMFIwBz1KIS2wb6$FllN97Ct8mpqPpxhloGDo0s9HaHZeWb" +
		"HbtudKZWkXTfDoSrOtm3c6a1$1jiPx9z4EubsalsRqkU26SRsWf6BMXwuzM$npEur");

	static final Action RETURN2 = new Action() {
		public Symbol reduce(Symbol[] _symbols, int offset) {
			return _symbols[offset + 2];
		}
	};
 
	public HashMap<String,Node> symtab = new HashMap<String,Node> ();	//ref du td6 a completer
	
	//public Stm statement;	//pour utiliser les methodes... a completer
	
	static class Events extends beaver.Parser.Events {
		public void syntaxError(Symbol token) {
			System.err.format("*** Erreur de syntaxe en ligne %d, colonne %d. Token inattendu: %s\n",
				Symbol.getLine(token.getStart()),
				Symbol.getColumn(token.getStart()),
				Terminals.NAMES[token.getId()]);
		}
	}
	
	public void semanticError(String msg, Symbol token) {
			System.err.format("*** " + msg + " ligne %d, colonne %d\n",
				Symbol.getLine(token.getStart()),
				Symbol.getColumn(token.getStart()));
		}
		
	private TypeEnvironment typeEnvironment = new TypeEnvironment("types");
	private ProcedureEnvironment procedureEnvironment = new ProcedureEnvironment("procedures");
	private StackEnvironment stackEnvironment = new StackEnvironment("local variables stack");
	private String type_declaration_name;
	
	private boolean critical_mode = false;

	private final Action[] actions;

	public Parser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			new Action() {	// [0] program = type_declaration_part.tp variable_declaration_part.vp procedure_definition_part.pp TOKEN_BEGIN push_stackenv.pu statement_list.l TOKEN_END pop_stackenv.pop
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol tp = _symbols[offset + 1];
					final Symbol vp = _symbols[offset + 2];
					final Symbol _symbol_pp = _symbols[offset + 3];
					final ArrayList _list_pp = (ArrayList) _symbol_pp.value;
					final TypeFunct[] pp = _list_pp == null ? new TypeFunct[0] : (TypeFunct[]) _list_pp.toArray(new TypeFunct[_list_pp.size()]);
					final Symbol pu = _symbols[offset + 5];
					final Symbol _symbol_l = _symbols[offset + 6];
					final NodeList l = (NodeList) _symbol_l.value;
					final Symbol pop = _symbols[offset + 8];
					 
	l.generateIntermediateCode();
      return _symbol_l;
				}
			},
			Action.NONE,  	// [1] type_declaration_part = 
			RETURN2,	// [2] type_declaration_part = TOKEN_TYPE type_declaration_list; returns 'type_declaration_list' although none is marked
			new Action() {	// [3] type_declaration_list = type_declaration_list type_declaration
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [4] type_declaration_list = type_declaration
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [5] type_declaration = TOKEN_IDENTIFIER.name TOKEN_AFF type.t TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_name = _symbols[offset + 1];
					final String name = (String) _symbol_name.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Type t = (Type) _symbol_t.value;
					
			try{
				//System.out.println("Registering type:" + t.toString());
				typeEnvironment.putVariable(name, t);
			} catch (DuplicateTypeDeclaration e) {//|UnknownType e) {
				System.err.println(e);
			} finally {
				return new EmptySymbol();
			}
				}
			},
			Action.RETURN,	// [6] type = simple_type
			Action.RETURN,	// [7] type = named_type
			Action.RETURN,	// [8] type = index_type
			Action.RETURN,	// [9] type = array_type
			Action.RETURN,	// [10] type = pointer_type
			Action.RETURN,	// [11] type = structure_type
			new Action() {	// [12] simple_type = TOKEN_STRING
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TypeString();
				}
			},
			new Action() {	// [13] simple_type = TOKEN_INTEGER
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TypeInt();
				}
			},
			new Action() {	// [14] simple_type = TOKEN_BOOLEAN
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TypeBoolean();
				}
			},
			new Action() {	// [15] named_type = TOKEN_IDENTIFIER.r
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_r = _symbols[offset + 1];
					final String r = (String) _symbol_r.value;
					 
		System.out.println("Named: " + r); 
		try {
			return typeEnvironment.getVariableValue(r);
		} catch(UnknownType e) {	//Si pas deja present
			System.err.println(e);
			return new TypeNamed(r);
		}
				}
			},
			Action.RETURN,	// [16] index_type = enumerated_type
			Action.RETURN,	// [17] index_type = subrange_type
			new Action() {	// [18] enumerated_type = init_enumerated_type TOKEN_LPAR identifier_list.id_l TOKEN_RPAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_id_l = _symbols[offset + 3];
					final IdentifierList id_l = (IdentifierList) _symbol_id_l.value;
					 
																		Vector<Type> array_tmp = new Vector<>();
																		int const_id = 0;
																		for(String identifier : id_l) {
																			array_tmp.add(new TypeItemEnum(const_id, identifier));
																			const_id +=1;
																		}
																		return new TypeTuple(array_tmp);
				}
			},
			Action.NONE,  	// [19] init_enumerated_type = 
			new Action() {	// [20] subrange_type = TOKEN_LIT_INTEGER.min TOKEN_DOTDOT TOKEN_LIT_INTEGER.max
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_min = _symbols[offset + 1];
					final Integer min = (Integer) _symbol_min.value;
					final Symbol _symbol_max = _symbols[offset + 3];
					final Integer max = (Integer) _symbol_max.value;
					 return new TypeArrayRange(new TypeInt(min), new TypeInt(max));
				}
			},
			new Action() {	// [21] subrange_type = TOKEN_IDENTIFIER.id_min TOKEN_DOTDOT TOKEN_IDENTIFIER.id_max
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_id_min = _symbols[offset + 1];
					final String id_min = (String) _symbol_id_min.value;
					final Symbol _symbol_id_max = _symbols[offset + 3];
					final String id_max = (String) _symbol_id_max.value;
						
																		try {
																			int val_min = typeEnvironment.getEnumType(id_min).getValue();
																			int val_max = typeEnvironment.getEnumType(id_max).getValue();
																			
																			return new TypeArrayRange(new TypeInt(val_min), new TypeInt(val_max));
																			
																		} catch (NoSuchFieldException e) {
																			System.err.println("subrange_type: " + e);
																			return new TypeArrayRange(new TypeInt(0), new TypeInt(0));
																		}
				}
			},
			new Action() {	// [22] array_type = TOKEN_ARRAY TOKEN_LBRACKET range_type.range TOKEN_RBRACKET TOKEN_OF type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_range = _symbols[offset + 3];
					final Type range = (Type) _symbol_range.value;
					final Symbol _symbol_t = _symbols[offset + 6];
					final Type t = (Type) _symbol_t.value;
					 return new TypeArray(range, t);
				}
			},
			Action.RETURN,	// [23] range_type = enumerated_type
			Action.RETURN,	// [24] range_type = subrange_type
			Action.RETURN,	// [25] range_type = named_type
			new Action() {	// [26] pointer_type = TOKEN_CIRC type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 2];
					final Type t = (Type) _symbol_t.value;
					 return new TypePointer(t);
				}
			},
			new Action() {	// [27] structure_type = TOKEN_STRUCT TOKEN_LBRACE feature_list_type.list TOKEN_RBRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 3];
					final TypeFeatureList list = (TypeFeatureList) _symbol_list.value;
					 return new TypeStruct(list);
				}
			},
			new Action() {	// [28] feature_list_type = feature_list_type.list feature_type.elem
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final TypeFeatureList list = (TypeFeatureList) _symbol_list.value;
					final Symbol _symbol_elem = _symbols[offset + 2];
					final TypeFeature elem = (TypeFeature) _symbol_elem.value;
					 list.add(elem); return list;
				}
			},
			new Action() {	// [29] feature_list_type = feature_type.elem
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_elem = _symbols[offset + 1];
					final TypeFeature elem = (TypeFeature) _symbol_elem.value;
					 TypeFeatureList list = new TypeFeatureList(elem); return list;
				}
			},
			new Action() {	// [30] feature_type = TOKEN_IDENTIFIER.id TOKEN_COLON type.t TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_id = _symbols[offset + 1];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Type t = (Type) _symbol_t.value;
					 System.out.println("FEATURES"); return new TypeFeature(id, t);
				}
			},
			Action.NONE,  	// [31] variable_declaration_part = 
			RETURN2,	// [32] variable_declaration_part = TOKEN_VAR variable_declaration_list; returns 'variable_declaration_list' although none is marked
			new Action() {	// [33] variable_declaration_list = variable_declaration_list variable_declaration
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2]); return _symbols[offset + 1];
				}
			},
			new Action() {	// [34] variable_declaration_list = variable_declaration
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1]); return new Symbol(lst);
				}
			},
			new Action() {	// [35] variable_declaration = identifier_list.id_list TOKEN_COLON type.t TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_id_list = _symbols[offset + 1];
					final IdentifierList id_list = (IdentifierList) _symbol_id_list.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Type t = (Type) _symbol_t.value;
					
																for(String str : id_list){
																	stackEnvironment.add_node_to_latest_portability(str, t);
																}
																
																return _symbol_id_list;
				}
			},
			new Action() {	// [36] identifier_list = identifier_list.list TOKEN_COMMA TOKEN_IDENTIFIER.id
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final IdentifierList list = (IdentifierList) _symbol_list.value;
					final Symbol _symbol_id = _symbols[offset + 3];
					final String id = (String) _symbol_id.value;
					 
																	list.add(id); return list;
				}
			},
			new Action() {	// [37] identifier_list = TOKEN_IDENTIFIER.name
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_name = _symbols[offset + 1];
					final String name = (String) _symbol_name.value;
					 
																	return new IdentifierList(name);
				}
			},
			Action.NONE,  	// [38] procedure_definition_part = 
			Action.RETURN,	// [39] procedure_definition_part = procedure_definition_list
			new Action() {	// [40] procedure_definition_list = procedure_definition_list procedure_definition
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [41] procedure_definition_list = procedure_definition
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [42] procedure_definition = procedure_definition_head.type_fct block.fct_content
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_type_fct = _symbols[offset + 1];
					final TypeFunct type_fct = (TypeFunct) _symbol_type_fct.value;
					final Symbol _symbol_fct_content = _symbols[offset + 2];
					final NodeList fct_content = (NodeList) _symbol_fct_content.value;
					 
			type_fct.setDefined(true);
			try {
				procedureEnvironment.putVariable(type_fct.getName(), type_fct); 
			} catch (AlreadyDefinedFunction e) {
				System.err.println(e);
				if(critical_mode)
					System.exit(0);
			}
		
			return type_fct;
				}
			},
			new Action() {	// [43] procedure_definition = procedure_declaration_head.type_fct TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_type_fct = _symbols[offset + 1];
					final TypeFunct type_fct = (TypeFunct) _symbol_type_fct.value;
					 
			type_fct.setDefined(false); 
			try {
				procedureEnvironment.putVariable(type_fct.getName(), type_fct); 
			} catch (AlreadyDefinedFunction e) {
				System.err.println(e);
				if(critical_mode)
					System.exit(0);
			}

			return type_fct;
				}
			},
			Action.RETURN,	// [44] procedure_definition_head = procedure_head.type_fct
			Action.RETURN,	// [45] procedure_declaration_head = procedure_head.type_fct
			new Action() {	// [46] procedure_head = TOKEN_PROCEDURE TOKEN_IDENTIFIER.funct_name TOKEN_LPAR argt_part.args TOKEN_RPAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_funct_name = _symbols[offset + 2];
					final String funct_name = (String) _symbol_funct_name.value;
					final Symbol _symbol_args = _symbols[offset + 4];
					final NodeList args = (NodeList) _symbol_args.value;
									
				TypeTuple params_tuple = new TypeTuple();
				
				for(Node n : args.getList()) {
					NodeId n_id = (NodeId) n;
					params_tuple.add(new TypeFeature(n_id.getName(), n_id.getType()));
					stackEnvironment.add_node_to_latest_portability(n_id.getName(), n_id.getType());
				}
				
				TypeFunct type_function = new TypeFunct(funct_name, params_tuple, new TypeVoid());
				
				return type_function;
				//return new NodeCallFct(funct_name, type_function, new NodeList());
				}
			},
			new Action() {	// [47] procedure_head = TOKEN_FUNCTION TOKEN_IDENTIFIER.funct_name TOKEN_LPAR argt_part.args TOKEN_RPAR TOKEN_COLON type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_funct_name = _symbols[offset + 2];
					final String funct_name = (String) _symbol_funct_name.value;
					final Symbol _symbol_args = _symbols[offset + 4];
					final NodeList args = (NodeList) _symbol_args.value;
					final Symbol _symbol_t = _symbols[offset + 7];
					final Type t = (Type) _symbol_t.value;
					
				TypeTuple params_tuple = new TypeTuple();
				
				for(Node n : args.getList()) {
					NodeId n_id = (NodeId) n;
					params_tuple.add(new TypeFeature(n_id.getName(), n_id.getType()));
					stackEnvironment.add_node_to_latest_portability(n_id.getName(), n_id.getType());
				}
				
				TypeFunct type_function = new TypeFunct(funct_name, params_tuple, t);
			
				return type_function;
				//return new NodeCallFct(funct_name, type_function, new NodeList());
				}
			},
			Action.NONE,  	// [48] argt_part = 
			Action.RETURN,	// [49] argt_part = argt_list
			new Action() {	// [50] argt_list = argt_list.nl TOKEN_COMMA argt.elem
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_nl = _symbols[offset + 1];
					final NodeList nl = (NodeList) _symbol_nl.value;
					final Symbol _symbol_elem = _symbols[offset + 3];
					final NodeId elem = (NodeId) _symbol_elem.value;
					 nl.add(elem); return nl;
				}
			},
			new Action() {	// [51] argt_list = argt.elem
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_elem = _symbols[offset + 1];
					final NodeId elem = (NodeId) _symbol_elem.value;
					 NodeList nl = new NodeList(elem); return nl;
				}
			},
			new Action() {	// [52] argt = TOKEN_IDENTIFIER.id TOKEN_COLON type.t
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_id = _symbols[offset + 1];
					final String id = (String) _symbol_id.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Type t = (Type) _symbol_t.value;
					 return new NodeId(id, t);
				}
			},
			new Action() {	// [53] block = variable_declaration_part TOKEN_BEGIN push_stackenv statement_list.list TOKEN_END pop_stackenv
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 4];
					final NodeList list = (NodeList) _symbol_list.value;
					 return _symbol_list;
				}
			},
			new Action() {	// [54] pop_stackenv = 
				public Symbol reduce(Symbol[] _symbols, int offset) {
						
						//System.out.println("[STACK] Poped one more stack layer"); 
						stackEnvironment.getEnvironment().pop(); 
						return new EmptySymbol();
				}
			},
			new Action() {	// [55] push_stackenv = 
				public Symbol reduce(Symbol[] _symbols, int offset) {
						
						//System.out.println("[STACK] Pushed one more stack layer"); 
						stackEnvironment.getEnvironment().push(new HashMap<String, Type>(stackEnvironment.getEnvironment().peek())); 
						return new EmptySymbol();
				}
			},
			new Action() {	// [56] statement_list = statement_list.root statement.elt
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_root = _symbols[offset + 1];
					final NodeList root = (NodeList) _symbol_root.value;
					final Symbol _symbol_elt = _symbols[offset + 2];
					final Node elt = (Node) _symbol_elt.value;
					 root.add(elt); return root;
				}
			},
			new Action() {	// [57] statement_list = statement.elt
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_elt = _symbols[offset + 1];
					final Node elt = (Node) _symbol_elt.value;
					 return new NodeList(elt);
				}
			},
			Action.RETURN,	// [58] statement = simple_statement
			Action.RETURN,	// [59] statement = structured_statement
			Action.RETURN,	// [60] simple_statement = assignment_statement
			Action.RETURN,	// [61] simple_statement = procedure_statement
			Action.RETURN,	// [62] simple_statement = new_statement
			Action.RETURN,	// [63] simple_statement = dispose_statement
			Action.RETURN,	// [64] simple_statement = println_statement
			Action.RETURN,	// [65] simple_statement = readln_statement
			Action.RETURN,	// [66] simple_statement = return_statement
			new Action() {	// [67] assignment_statement = variable_access.e1 TOKEN_AFF expression.e2 TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					  
		//System.out.println("Left: " + e1.toString());
		//System.out.println("Right: " + e2.toString());
																return new NodeAssign(e1, e2);
				}
			},
			new Action() {	// [68] procedure_statement = procedure_expression.n TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final NodeCallFct n = (NodeCallFct) _symbol_n.value;
					 return n;
				}
			},
			new Action() {	// [69] procedure_expression = TOKEN_IDENTIFIER.func_name TOKEN_LPAR expression_part.args TOKEN_RPAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_func_name = _symbols[offset + 1];
					final String func_name = (String) _symbol_func_name.value;
					final Symbol _symbol_args = _symbols[offset + 3];
					final NodeList args = (NodeList) _symbol_args.value;
					 
																				try{
																					stackEnvironment.getEnvironment().push(new HashMap<String, Type>(stackEnvironment.getEnvironment().peek())); //push env
																					HashMap<String, Type> table = (HashMap) stackEnvironment.getEnvironment().peek();
																					
																					//NodeCallFct fct_from_table = procedureEnvironment.getNodeFct(func_name);
																					//TypeFunct fct_type = fct_from_table.getTypeFunct().clone();
																					TypeFunct fct_type = procedureEnvironment.getNodeFct(func_name);
																					
																					int i = 0;
																					Iterator<Type> it = fct_type.getParams().iterator();
																					while(it.hasNext()) {
																						TypeFeature current_type = (TypeFeature) it.next();
																						String id = current_type.getName();
																						Type t = current_type.getType();
																						if((args.get(i) instanceof NodeLiteral)) {
																							NodeLiteral node = (NodeLiteral) args.get(i);
																							table.put(id, node.getType());		
																							System.out.println("Register function NodeLiteral:" +id + " | "+ node.toString());
																						}else if(args.get(i) instanceof NodeOp) {
																							NodeLiteral node = new NodeLiteral(new TypeInt(), args.get(i));
																							table.put(id, node.getType());
																							System.out.println("Register function NodOp:" +id + " | "+ node.toString());
																					
																						}else if(args.get(i) instanceof NodeRel) {
																							NodeLiteral node = new NodeLiteral(new TypeBoolean(), args.get(i));
																							table.put(id, node.getType());
																							System.out.println("Register function NodeRel:" +id + " | "+ node.toString());
																							
																						}else {
																							System.out.println("Cannot register node: " + args.get(i).toString());
																						}
																								
																						
																						
																						i++;
																					}
																					
																					return new NodeCallFct(func_name, fct_type, args);
																				}catch(NoSuchFieldException e){
																					System.out.println("Procedure Expression: " + e);
																					return new NodeCallFct(func_name, new TypeFunct(func_name, new TypeTuple(), new TypeVoid()), args);
																				}
				}
			},
			Action.NONE,  	// [70] expression_part = 
			Action.RETURN,	// [71] expression_part = expression_list
			new Action() {	// [72] expression_list = expression_list.root TOKEN_COMMA expression.elt
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_root = _symbols[offset + 1];
					final NodeList root = (NodeList) _symbol_root.value;
					final Symbol _symbol_elt = _symbols[offset + 3];
					final NodeExp elt = (NodeExp) _symbol_elt.value;
					 root.add(elt); return root;
				}
			},
			new Action() {	// [73] expression_list = expression.expr
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_expr = _symbols[offset + 1];
					final NodeExp expr = (NodeExp) _symbol_expr.value;
					 return new NodeList(expr);
				}
			},
			new Action() {	// [74] new_statement = TOKEN_NEW variable_access.node TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 2];
					final NodeExp node = (NodeExp) _symbol_node.value;
					 
		if(node instanceof NodeId) {
			NodeId n_id = (NodeId) node;
			try {
				stackEnvironment.alloc_variable(n_id.getName()); 
			}catch(MemoryLeak e) {
				System.err.println(e);
				if(critical_mode)
					System.exit(0);
				return node;
			}
		}
		return new NodeNew(node);
				}
			},
			new Action() {	// [75] dispose_statement = TOKEN_DISPOSE variable_access.node TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 2];
					final NodeExp node = (NodeExp) _symbol_node.value;
					 
								if(node instanceof NodeId) {
									NodeId n_id = (NodeId) node;
									try {
										stackEnvironment.dispose_variable(n_id.getName()); 
									}catch(MemoryLeak e) {
										System.err.println(e);
										if(critical_mode)
											System.exit(0);
										return node;
									}
								}
								return new NodeDispose(node);
				}
			},
			new Action() {	// [76] println_statement = TOKEN_PRINTLN expression.args TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_args = _symbols[offset + 2];
					final NodeExp args = (NodeExp) _symbol_args.value;
					 
				TypeTuple params_tuple = null;

				if(args instanceof NodeCallFct) {
					NodeCallFct tmp = (NodeCallFct) args;
					params_tuple= new TypeTuple(new TypeFeature(tmp.getName(), tmp.getType()));
				} else {
					params_tuple= new TypeTuple(new TypeFeature("println nodelist", args.getType()));
				}

				
				return new NodeCallFct(
						"println",
						new TypeFunct("println", params_tuple, new TypeVoid()),
						new NodeList(args));
				}
			},
			new Action() {	// [77] readln_statement = TOKEN_READLN expression.e TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final NodeExp e = (NodeExp) _symbol_e.value;
					 
			return new NodeCallFct(
				"readln", 
				new TypeFunct("readln", 
					new TypeTuple(e.getType()), 
					e.getType()),
				new NodeList());
				}
			},
			new Action() {	// [78] return_statement = TOKEN_RETURN expression.node TOKEN_SEMIC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_node = _symbols[offset + 2];
					final NodeExp node = (NodeExp) _symbol_node.value;
					 return new NodeReturn(node);
				}
			},
			Action.RETURN,	// [79] structured_statement = block
			Action.RETURN,	// [80] structured_statement = if_statement
			Action.RETURN,	// [81] structured_statement = while_statement
			Action.RETURN,	// [82] structured_statement = switch_statement
			new Action() {	// [83] if_statement = TOKEN_IF expression.e TOKEN_THEN statement.stm
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final NodeExp e = (NodeExp) _symbol_e.value;
					final Symbol _symbol_stm = _symbols[offset + 4];
					final Node stm = (Node) _symbol_stm.value;
						return new NodeIf(e, stm);
				}
			},
			new Action() {	// [84] if_statement = TOKEN_IF expression.e TOKEN_THEN statement.stm_then TOKEN_ELSE statement.stm_else
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final NodeExp e = (NodeExp) _symbol_e.value;
					final Symbol _symbol_stm_then = _symbols[offset + 4];
					final Node stm_then = (Node) _symbol_stm_then.value;
					final Symbol _symbol_stm_else = _symbols[offset + 6];
					final Node stm_else = (Node) _symbol_stm_else.value;
						return new NodeIf(e, stm_then, stm_else);
				}
			},
			new Action() {	// [85] while_statement = TOKEN_WHILE expression.e1 TOKEN_DO statement.stm
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 2];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_stm = _symbols[offset + 4];
					final Node stm = (Node) _symbol_stm.value;
						return new NodeWhile(e1, stm);
				}
			},
			new Action() {	// [86] switch_statement = TOKEN_SWITCH expression.root TOKEN_BEGIN case_statement_list.case_list TOKEN_END
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_root = _symbols[offset + 2];
					final NodeExp root = (NodeExp) _symbol_root.value;
					final Symbol _symbol_case_list = _symbols[offset + 4];
					final NodeCaseList case_list = (NodeCaseList) _symbol_case_list.value;
					 return new NodeSwitch(root, case_list);
				}
			},
			new Action() {	// [87] case_statement_list = case_statement_list.list case_statement.item
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_list = _symbols[offset + 1];
					final NodeCaseList list = (NodeCaseList) _symbol_list.value;
					final Symbol _symbol_item = _symbols[offset + 2];
					final NodeCaseList item = (NodeCaseList) _symbol_item.value;
					 
				List<Node> lst_entry = item.getList();
				for(Node n : lst_entry) {
					NodeCase n_case = (NodeCase) n;
					list.add(n_case); 
				}
				return list;
				}
			},
			Action.RETURN,	// [88] case_statement_list = case_statement.list
			new Action() {	// [89] case_statement = TOKEN_CASE identifier_list.idl TOKEN_COLON statement.st
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_idl = _symbols[offset + 2];
					final IdentifierList idl = (IdentifierList) _symbol_idl.value;
					final Symbol _symbol_st = _symbols[offset + 4];
					final Node st = (Node) _symbol_st.value;
					 
				NodeCaseList res = new NodeCaseList();
				for(String id : idl) {
					res.add(new NodeCase(id, st));
				}
				
				return res;
				}
			},
			new Action() {	// [90] case_statement = TOKEN_DEFAULT TOKEN_COLON statement.state
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_state = _symbols[offset + 3];
					final Node state = (Node) _symbol_state.value;
					 return new NodeCaseList(new NodeCase(state));
				}
			},
			new Action() {	// [91] variable_access = TOKEN_IDENTIFIER.name
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_name = _symbols[offset + 1];
					final String name = (String) _symbol_name.value;
						
			try{
				Type t = stackEnvironment.get_node_reachable(name);  
				return new NodeId(name, t);
			} catch (UnknownVariable e) {	//Not a normal variable
				try {						//Check enum
					Type tmp = typeEnvironment.getEnumType(name);
					if(tmp instanceof TypeItemEnum) {
						TypeItemEnum t = (TypeItemEnum) tmp;
						return new NodeId(t.getRefEnumRange(), new TypeInt(t.getValue()));
					}
					return new NodeId(null, null);					
					
					//System.out.println("FINDDD");
				} catch (NoSuchFieldException e2) {

					//System.err.println("Variable [" + name + "]");
					System.err.println(e2);
					return new NodeId(null, null);
				}
			}
				}
			},
			new Action() {	// [92] variable_access = variable_access.var TOKEN_LBRACKET expression.e TOKEN_RBRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_var = _symbols[offset + 1];
					final NodeExp var = (NodeExp) _symbol_var.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final NodeExp e = (NodeExp) _symbol_e.value;
					 return new NodeArrayAccess(var, e);
				}
			},
			new Action() {	// [93] variable_access = expression.e TOKEN_CIRC
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final NodeExp e = (NodeExp) _symbol_e.value;
					 
		if(!(e.getType() instanceof TypePointer)){
			System.err.println("[MEMLEAK] Trying to access free or undeclared pointer");
			
			if(critical_mode)
				System.exit(0);
			return e;
		}
		return new NodePtrAccess(e);
				}
			},
			new Action() {	// [94] expression = expression.e1 TOKEN_PLUS expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp("plus", e1, e2);
				}
			},
			new Action() {	// [95] expression = expression.e1 TOKEN_MINUS expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp("minus", e1, e2);
				}
			},
			new Action() {	// [96] expression = expression.e1 TOKEN_TIMES expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp("times", e1, e2);
				}
			},
			new Action() {	// [97] expression = expression.e1 TOKEN_DIV expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeOp("divide", e1, e2);
				}
			},
			new Action() {	// [98] expression = TOKEN_MINUS expression.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final NodeExp e = (NodeExp) _symbol_e.value;
					 return new NodeOp("u_minus", e);
				}
			},
			new Action() {	// [99] expression = expression.e1 TOKEN_OR expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("or", e1, e2);
				}
			},
			new Action() {	// [100] expression = expression.e1 TOKEN_AND expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("an", e1, e2);
				}
			},
			new Action() {	// [101] expression = TOKEN_NOT expression.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final NodeExp e = (NodeExp) _symbol_e.value;
					 return new NodeRel("no", e, new NodeLiteral(new TypeBoolean(), false));
				}
			},
			new Action() {	// [102] expression = expression.e1 TOKEN_LT expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("lt", e1, e2);
				}
			},
			new Action() {	// [103] expression = expression.e1 TOKEN_LE expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("le", e1, e2);
				}
			},
			new Action() {	// [104] expression = expression.e1 TOKEN_GT expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("gt", e1, e2);
				}
			},
			new Action() {	// [105] expression = expression.e1 TOKEN_GE expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("ge", e1, e2);
				}
			},
			new Action() {	// [106] expression = expression.e1 TOKEN_EQ expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("eq", e1, e2);
				}
			},
			new Action() {	// [107] expression = expression.e1 TOKEN_NE expression.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final NodeExp e1 = (NodeExp) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final NodeExp e2 = (NodeExp) _symbol_e2.value;
					 return new NodeRel("ne", e1, e2);
				}
			},
			new Action() {	// [108] expression = TOKEN_LPAR expression.e TOKEN_RPAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final NodeExp e = (NodeExp) _symbol_e.value;
					 return e;
				}
			},
			Action.RETURN,	// [109] expression = procedure_expression
			Action.RETURN,	// [110] expression = variable_access
			Action.RETURN,	// [111] expression = literal
			new Action() {	// [112] literal = TOKEN_LIT_INTEGER.value
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_value = _symbols[offset + 1];
					final Integer value = (Integer) _symbol_value.value;
					 return new NodeLiteral(new TypeInt(), value);
				}
			},
			new Action() {	// [113] literal = TOKEN_LIT_STRING.value
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_value = _symbols[offset + 1];
					final String value = (String) _symbol_value.value;
					 return new NodeLiteral(new TypeString(), value);
				}
			},
			new Action() {	// [114] literal = TOKEN_TRUE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new NodeLiteral(new TypeBoolean(), true);
				}
			},
			new Action() {	// [115] literal = TOKEN_FALSE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new NodeLiteral(new TypeBoolean(), false);
				}
			},
			new Action() {	// [116] literal = TOKEN_NULL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new NodeLiteral(new TypeVoid(), null);
				}
			}
		};

 
	report = new Events();
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
