/* The following code was generated by JFlex 1.7.0 */

package ubordeaux.deptinfo.compilation.project.main;

import beaver.Symbol;
import beaver.Scanner;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/Users/Jordane/Desktop/Projets/Projet-Compilation/scanner/Scanner.jflex</tt>
 */
class ScannerExpr extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int COMMENT_DOC = 4;
  public static final int ANNOTATION = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\2\1\0\1\17\2\0\1\16\16\2\5\0\1\57\1\4\1\0"+
    "\1\1\1\0\1\61\1\0\1\43\1\44\1\24\1\41\1\51\1\42"+
    "\1\53\1\20\1\21\11\3\1\52\1\5\1\54\1\55\1\56\1\0"+
    "\1\63\6\23\24\1\1\45\1\0\1\46\1\62\1\23\1\0\1\13"+
    "\1\34\1\25\1\36\1\11\1\12\1\33\1\40\1\31\2\1\1\14"+
    "\1\64\1\32\1\30\1\27\1\1\1\7\1\15\1\6\1\10\1\37"+
    "\1\35\1\22\1\26\1\1\1\47\1\60\1\50\1\0\41\2\2\0"+
    "\4\1\4\0\1\1\2\0\1\2\7\0\1\1\4\0\1\1\5\0"+
    "\27\1\1\0\37\1\1\0\u01ca\1\4\0\14\1\16\0\5\1\7\0"+
    "\1\1\1\0\1\1\21\0\160\2\5\1\1\0\2\1\2\0\4\1"+
    "\10\0\1\1\1\0\3\1\1\0\1\1\1\0\24\1\1\0\123\1"+
    "\1\0\213\1\1\0\5\2\2\0\236\1\11\0\46\1\2\0\1\1"+
    "\7\0\47\1\7\0\1\1\1\0\55\2\1\0\1\2\1\0\2\2"+
    "\1\0\2\2\1\0\1\2\10\0\33\1\5\0\3\1\15\0\5\2"+
    "\6\0\1\1\4\0\13\2\5\0\53\1\37\2\4\0\2\1\1\2"+
    "\143\1\1\0\1\1\10\2\1\0\6\2\2\1\2\2\1\0\4\2"+
    "\2\1\12\2\3\1\2\0\1\1\17\0\1\2\1\1\1\2\36\1"+
    "\33\2\2\0\131\1\13\2\1\1\16\0\12\2\41\1\11\2\2\1"+
    "\4\0\1\1\5\0\26\1\4\2\1\1\11\2\1\1\3\2\1\1"+
    "\5\2\22\0\31\1\3\2\104\0\1\1\1\0\13\1\67\0\33\2"+
    "\1\0\4\2\66\1\3\2\1\1\22\2\1\1\7\2\12\1\2\2"+
    "\2\0\12\2\1\0\7\1\1\0\7\1\1\0\3\2\1\0\10\1"+
    "\2\0\2\1\2\0\26\1\1\0\7\1\1\0\1\1\3\0\4\1"+
    "\2\0\1\2\1\1\7\2\2\0\2\2\2\0\3\2\1\1\10\0"+
    "\1\2\4\0\2\1\1\0\3\1\2\2\2\0\12\2\4\1\7\0"+
    "\1\1\5\0\3\2\1\0\6\1\4\0\2\1\2\0\26\1\1\0"+
    "\7\1\1\0\2\1\1\0\2\1\1\0\2\1\2\0\1\2\1\0"+
    "\5\2\4\0\2\2\2\0\3\2\3\0\1\2\7\0\4\1\1\0"+
    "\1\1\7\0\14\2\3\1\1\2\13\0\3\2\1\0\11\1\1\0"+
    "\3\1\1\0\26\1\1\0\7\1\1\0\2\1\1\0\5\1\2\0"+
    "\1\2\1\1\10\2\1\0\3\2\1\0\3\2\2\0\1\1\17\0"+
    "\2\1\2\2\2\0\12\2\1\0\1\1\17\0\3\2\1\0\10\1"+
    "\2\0\2\1\2\0\26\1\1\0\7\1\1\0\2\1\1\0\5\1"+
    "\2\0\1\2\1\1\7\2\2\0\2\2\2\0\3\2\10\0\2\2"+
    "\4\0\2\1\1\0\3\1\2\2\2\0\12\2\1\0\1\1\20\0"+
    "\1\2\1\1\1\0\6\1\3\0\3\1\1\0\4\1\3\0\2\1"+
    "\1\0\1\1\1\0\2\1\3\0\2\1\3\0\3\1\3\0\14\1"+
    "\4\0\5\2\3\0\3\2\1\0\4\2\2\0\1\1\6\0\1\2"+
    "\16\0\12\2\11\0\1\1\7\0\3\2\1\0\10\1\1\0\3\1"+
    "\1\0\27\1\1\0\12\1\1\0\5\1\3\0\1\1\7\2\1\0"+
    "\3\2\1\0\4\2\7\0\2\2\1\0\2\1\6\0\2\1\2\2"+
    "\2\0\12\2\22\0\2\2\1\0\10\1\1\0\3\1\1\0\27\1"+
    "\1\0\12\1\1\0\5\1\2\0\1\2\1\1\7\2\1\0\3\2"+
    "\1\0\4\2\7\0\2\2\7\0\1\1\1\0\2\1\2\2\2\0"+
    "\12\2\1\0\2\1\17\0\2\2\1\0\10\1\1\0\3\1\1\0"+
    "\51\1\2\0\1\1\7\2\1\0\3\2\1\0\4\2\1\1\10\0"+
    "\1\2\10\0\2\1\2\2\2\0\12\2\12\0\6\1\2\0\2\2"+
    "\1\0\22\1\3\0\30\1\1\0\11\1\1\0\1\1\2\0\7\1"+
    "\3\0\1\2\4\0\6\2\1\0\1\2\1\0\10\2\22\0\2\2"+
    "\15\0\60\1\1\2\2\1\7\2\4\0\10\1\10\2\1\0\12\2"+
    "\47\0\2\1\1\0\1\1\2\0\2\1\1\0\1\1\2\0\1\1"+
    "\6\0\4\1\1\0\7\1\1\0\3\1\1\0\1\1\1\0\1\1"+
    "\2\0\2\1\1\0\4\1\1\2\2\1\6\2\1\0\2\2\1\1"+
    "\2\0\5\1\1\0\1\1\1\0\6\2\2\0\12\2\2\0\4\1"+
    "\40\0\1\1\27\0\2\2\6\0\12\2\13\0\1\2\1\0\1\2"+
    "\1\0\1\2\4\0\2\2\10\1\1\0\44\1\4\0\24\2\1\0"+
    "\2\2\5\1\13\2\1\0\44\2\11\0\1\2\71\0\53\1\24\2"+
    "\1\1\12\2\6\0\6\1\4\2\4\1\3\2\1\1\3\2\2\1"+
    "\7\2\3\1\4\2\15\1\14\2\1\1\17\2\2\0\46\1\1\0"+
    "\1\1\5\0\1\1\2\0\53\1\1\0\u014d\1\1\0\4\1\2\0"+
    "\7\1\1\0\1\1\1\0\4\1\2\0\51\1\1\0\4\1\2\0"+
    "\41\1\1\0\4\1\2\0\7\1\1\0\1\1\1\0\4\1\2\0"+
    "\17\1\1\0\71\1\1\0\4\1\2\0\103\1\2\0\3\2\40\0"+
    "\20\1\20\0\125\1\14\0\u026c\1\2\0\21\1\1\0\32\1\5\0"+
    "\113\1\3\0\3\1\17\0\15\1\1\0\4\1\3\2\13\0\22\1"+
    "\3\2\13\0\22\1\2\2\14\0\15\1\1\0\3\1\1\0\2\2"+
    "\14\0\64\1\40\2\3\0\1\1\3\0\2\1\1\2\2\0\12\2"+
    "\41\0\3\2\2\0\12\2\6\0\130\1\10\0\51\1\1\2\1\1"+
    "\5\0\106\1\12\0\35\1\3\0\14\2\4\0\14\2\12\0\12\2"+
    "\36\1\2\0\5\1\13\0\54\1\4\0\21\2\7\1\2\2\6\0"+
    "\12\2\46\0\27\1\5\2\4\0\65\1\12\2\1\0\35\2\2\0"+
    "\13\2\6\0\12\2\15\0\1\1\130\0\5\2\57\1\21\2\7\1"+
    "\4\0\12\2\21\0\11\2\14\0\3\2\36\1\15\2\2\1\12\2"+
    "\54\1\16\2\14\0\44\1\24\2\10\0\12\2\3\0\3\1\12\2"+
    "\44\1\122\0\3\2\1\0\25\2\4\1\1\2\4\1\3\2\2\1"+
    "\11\0\300\1\47\2\25\0\4\2\u0116\1\2\0\6\1\2\0\46\1"+
    "\2\0\6\1\2\0\10\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\37\1\2\0\65\1\1\0\7\1\1\0\1\1\3\0\3\1"+
    "\1\0\7\1\3\0\4\1\2\0\6\1\4\0\15\1\5\0\3\1"+
    "\1\0\7\1\16\0\5\2\32\0\5\2\20\0\2\1\23\0\1\1"+
    "\13\0\5\2\5\0\6\2\1\0\1\1\15\0\1\1\20\0\15\1"+
    "\3\0\33\1\25\0\15\2\4\0\1\2\3\0\14\2\21\0\1\1"+
    "\4\0\1\1\2\0\12\1\1\0\1\1\3\0\5\1\6\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\4\1\1\0\13\1\2\0\4\1"+
    "\5\0\5\1\4\0\1\1\21\0\51\1\u0a77\0\57\1\1\0\57\1"+
    "\1\0\205\1\6\0\4\1\3\2\2\1\14\0\46\1\1\0\1\1"+
    "\5\0\1\1\2\0\70\1\7\0\1\1\17\0\1\2\27\1\11\0"+
    "\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0"+
    "\7\1\1\0\7\1\1\0\7\1\1\0\40\2\57\0\1\1\u01d5\0"+
    "\3\1\31\0\11\1\6\2\1\0\5\1\2\0\5\1\4\0\126\1"+
    "\2\0\2\2\2\0\3\1\1\0\132\1\1\0\4\1\5\0\51\1"+
    "\3\0\136\1\21\0\33\1\65\0\20\1\u0200\0\u19b6\1\112\0\u51cd\1"+
    "\63\0\u048d\1\103\0\56\1\2\0\u010d\1\3\0\20\1\12\2\2\1"+
    "\24\0\57\1\1\2\4\0\12\2\1\0\31\1\7\0\1\2\120\1"+
    "\2\2\45\0\11\1\2\0\147\1\2\0\4\1\1\0\4\1\14\0"+
    "\13\1\115\0\12\1\1\2\3\1\1\2\4\1\1\2\27\1\5\2"+
    "\20\0\1\1\7\0\64\1\14\0\2\2\62\1\21\2\13\0\12\2"+
    "\6\0\22\2\6\1\3\0\1\1\4\0\12\2\34\1\10\2\2\0"+
    "\27\1\15\2\14\0\35\1\3\0\4\2\57\1\16\2\16\0\1\1"+
    "\12\2\46\0\51\1\16\2\11\0\3\1\1\2\10\1\2\2\2\0"+
    "\12\2\6\0\27\1\3\0\1\1\1\2\4\0\60\1\1\2\1\1"+
    "\3\2\2\1\2\2\5\1\2\2\1\1\1\2\1\1\30\0\3\1"+
    "\2\0\13\1\5\2\2\0\3\1\2\2\12\0\6\1\2\0\6\1"+
    "\2\0\6\1\11\0\7\1\1\0\7\1\221\0\43\1\10\2\1\0"+
    "\2\2\2\0\12\2\6\0\u2ba4\1\14\0\27\1\4\0\61\1\u2104\0"+
    "\u016e\1\2\0\152\1\46\0\7\1\14\0\5\1\5\0\1\1\1\2"+
    "\12\1\1\0\15\1\1\0\5\1\1\0\1\1\1\0\2\1\1\0"+
    "\2\1\1\0\154\1\41\0\u016b\1\22\0\100\1\2\0\66\1\50\0"+
    "\15\1\3\0\20\2\20\0\7\2\14\0\2\1\30\0\3\1\31\0"+
    "\1\1\6\0\5\1\1\0\207\1\2\0\1\2\4\0\1\1\13\0"+
    "\12\2\7\0\32\1\4\0\1\1\1\0\32\1\13\0\131\1\3\0"+
    "\6\1\2\0\6\1\2\0\6\1\2\0\3\1\3\0\2\1\3\0"+
    "\2\1\22\0\3\2\4\0\14\1\1\0\32\1\1\0\23\1\1\0"+
    "\2\1\1\0\17\1\2\0\16\1\42\0\173\1\105\0\65\1\210\0"+
    "\1\2\202\0\35\1\3\0\61\1\57\0\37\1\21\0\33\1\65\0"+
    "\36\1\2\0\44\1\4\0\10\1\1\0\5\1\52\0\236\1\2\0"+
    "\12\2\u0356\0\6\1\2\0\1\1\1\0\54\1\1\0\2\1\3\0"+
    "\1\1\2\0\27\1\252\0\26\1\12\0\32\1\106\0\70\1\6\0"+
    "\2\1\100\0\1\1\3\2\1\0\2\2\5\0\4\2\4\1\1\0"+
    "\3\1\1\0\33\1\4\0\3\2\4\0\1\2\40\0\35\1\203\0"+
    "\66\1\12\0\26\1\12\0\23\1\215\0\111\1\u03b7\0\3\2\65\1"+
    "\17\2\37\0\12\2\20\0\3\2\55\1\13\2\2\0\1\2\22\0"+
    "\31\1\7\0\12\2\6\0\3\2\44\1\16\2\1\0\12\2\100\0"+
    "\3\2\60\1\16\2\4\1\13\0\12\2\u04a6\0\53\1\15\2\10\0"+
    "\12\2\u0936\0\u036f\1\221\0\143\1\u0b9d\0\u042f\1\u33d1\0\u0239\1\u04c7\0"+
    "\105\1\13\0\1\1\56\2\20\0\4\2\15\1\u4060\0\2\1\u2163\0"+
    "\5\2\3\0\26\2\2\0\7\2\36\0\4\2\224\0\3\2\u01bb\0"+
    "\125\1\1\0\107\1\1\0\2\1\2\0\1\1\2\0\2\1\2\0"+
    "\4\1\1\0\14\1\1\0\1\1\1\0\7\1\1\0\101\1\1\0"+
    "\4\1\2\0\10\1\1\0\7\1\1\0\34\1\1\0\4\1\1\0"+
    "\5\1\1\0\1\1\3\0\7\1\1\0\u0154\1\2\0\31\1\1\0"+
    "\31\1\1\0\37\1\1\0\31\1\1\0\37\1\1\0\31\1\1\0"+
    "\37\1\1\0\31\1\1\0\37\1\1\0\31\1\1\0\10\1\2\0"+
    "\62\2\u1600\0\4\1\1\0\33\1\1\0\2\1\1\0\1\1\2\0"+
    "\1\1\1\0\12\1\1\0\4\1\1\0\1\1\1\0\1\1\6\0"+
    "\1\1\4\0\1\1\1\0\1\1\1\0\1\1\1\0\3\1\1\0"+
    "\2\1\1\0\1\1\2\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\2\1\1\0\1\1\2\0\4\1\1\0"+
    "\7\1\1\0\4\1\1\0\4\1\1\0\1\1\1\0\12\1\1\0"+
    "\21\1\5\0\3\1\1\0\5\1\1\0\21\1\u1144\0\ua6d7\1\51\0"+
    "\u1035\1\13\0\336\1\u3fe2\0\u021e\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\2\36\0\140\2\200\0\360\2\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\1\1\4\6\2\1\5"+
    "\1\3\1\6\11\2\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\1\1\21\1\22"+
    "\1\23\1\24\2\1\1\25\3\26\1\27\5\30\2\0"+
    "\13\2\1\31\1\32\1\33\2\2\1\34\1\35\7\2"+
    "\1\36\2\2\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\4\0\1\50\6\2\1\51\5\2"+
    "\2\31\1\52\4\2\1\53\5\2\1\54\4\0\1\55"+
    "\1\56\1\57\2\2\1\60\6\2\1\61\2\2\1\62"+
    "\5\2\4\0\3\2\1\63\1\64\5\2\1\65\1\2"+
    "\1\66\2\2\2\0\1\67\1\0\1\70\1\71\1\2"+
    "\1\72\1\73\1\74\5\2\1\75\1\76\1\0\1\2"+
    "\1\77\1\100\1\101\1\102\1\103\1\104\1\105";

  private static int [] zzUnpackAction() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\324\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6"+
    "\0\u031b\0\324\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459"+
    "\0\u048e\0\u04c3\0\u04f8\0\324\0\324\0\324\0\324\0\324"+
    "\0\324\0\324\0\324\0\324\0\324\0\u052d\0\u0562\0\u0597"+
    "\0\u05cc\0\u0601\0\u0636\0\u066b\0\324\0\324\0\u06a0\0\u06d5"+
    "\0\324\0\324\0\u070a\0\u073f\0\u0774\0\u07a9\0\u0173\0\u07de"+
    "\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986"+
    "\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e"+
    "\0\u0109\0\u0109\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c"+
    "\0\u0ca1\0\u0109\0\u0cd6\0\u0d0b\0\324\0\324\0\324\0\324"+
    "\0\324\0\324\0\324\0\324\0\324\0\u0d40\0\u0d75\0\u0daa"+
    "\0\u0ddf\0\324\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d"+
    "\0\u0109\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\324"+
    "\0\324\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u0109\0\u1164\0\u1199"+
    "\0\u11ce\0\u1203\0\u1238\0\u0109\0\u126d\0\u12a2\0\u12d7\0\u130c"+
    "\0\u0109\0\u0109\0\u0109\0\u1341\0\u1376\0\u0109\0\u13ab\0\u13e0"+
    "\0\u1415\0\u144a\0\u147f\0\u14b4\0\u0109\0\u14e9\0\u151e\0\u0109"+
    "\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c\0\u1691\0\u16c6"+
    "\0\u16fb\0\u1730\0\u1765\0\u179a\0\u0109\0\u0109\0\u17cf\0\u1804"+
    "\0\u1839\0\u186e\0\u18a3\0\u0109\0\u18d8\0\u0109\0\u190d\0\u1942"+
    "\0\u1977\0\u19ac\0\324\0\u19e1\0\u0109\0\u0109\0\u1a16\0\u0109"+
    "\0\u0109\0\u0109\0\u1a4b\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f\0\324"+
    "\0\324\0\u1b54\0\u1b89\0\u0109\0\u0109\0\u0109\0\u0109\0\u0109"+
    "\0\324\0\u0109";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\5\1\7\1\10\1\11\1\12\1\13"+
    "\1\6\1\14\1\15\1\16\1\6\1\17\2\5\1\20"+
    "\1\21\2\6\1\22\1\23\1\6\1\24\1\25\1\26"+
    "\1\27\1\6\1\30\1\31\1\32\1\33\1\6\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\5\1\6\24\56\1\57\64\56\1\60\36\56"+
    "\1\61\1\56\7\62\1\63\3\62\1\64\13\62\1\65"+
    "\7\62\1\66\25\62\66\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\14\6\23\0\1\6\3\0\1\7\15\0"+
    "\1\7\43\0\4\67\1\70\60\67\1\0\3\6\2\0"+
    "\1\6\1\71\6\6\3\0\3\6\1\0\1\6\1\72"+
    "\11\6\1\73\23\0\1\6\1\0\3\6\2\0\3\6"+
    "\1\74\4\6\3\0\3\6\1\0\14\6\23\0\1\6"+
    "\1\0\3\6\2\0\6\6\1\75\1\6\3\0\3\6"+
    "\1\0\5\6\1\76\6\6\23\0\1\6\1\0\3\6"+
    "\2\0\2\6\1\77\2\6\1\100\2\6\3\0\3\6"+
    "\1\0\14\6\23\0\1\6\1\0\3\6\2\0\1\6"+
    "\1\101\6\6\3\0\3\6\1\0\14\6\23\0\1\6"+
    "\1\0\3\6\2\0\1\102\7\6\3\0\3\6\1\0"+
    "\10\6\1\103\3\6\23\0\1\6\20\0\1\104\3\0"+
    "\1\105\43\0\1\7\15\0\1\7\1\106\43\0\3\6"+
    "\2\0\5\6\1\107\2\6\3\0\3\6\1\0\14\6"+
    "\23\0\1\6\1\0\3\6\2\0\1\6\1\110\6\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\1\0\3\6"+
    "\2\0\4\6\1\111\3\6\3\0\3\6\1\0\14\6"+
    "\23\0\1\6\1\0\3\6\2\0\4\6\1\112\3\6"+
    "\3\0\3\6\1\0\5\6\1\113\6\6\23\0\1\6"+
    "\1\0\3\6\2\0\2\6\1\114\1\115\4\6\3\0"+
    "\3\6\1\0\14\6\23\0\1\6\1\0\3\6\2\0"+
    "\3\6\1\116\4\6\3\0\3\6\1\0\3\6\1\117"+
    "\10\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\13\6\1\120\23\0\1\6\1\0\3\6"+
    "\2\0\3\6\1\121\4\6\3\0\3\6\1\0\3\6"+
    "\1\122\1\123\7\6\23\0\1\6\1\0\3\6\2\0"+
    "\5\6\1\124\2\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\53\0\1\125\66\0\1\126\64\0\1\127\64\0"+
    "\1\130\64\0\1\131\67\0\1\132\65\0\1\133\23\0"+
    "\1\134\64\0\1\135\55\0\1\136\63\0\1\137\67\0"+
    "\1\140\62\0\1\141\60\0\1\142\60\0\3\6\2\0"+
    "\2\6\1\143\5\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\1\0\3\6\2\0\10\6\3\0\3\6\1\0"+
    "\2\6\1\144\11\6\23\0\1\6\1\0\3\6\2\0"+
    "\3\6\1\145\4\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\1\0\3\6\2\0\1\146\4\6\1\147\2\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\1\0\3\6"+
    "\2\0\7\6\1\150\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\1\0\3\6\2\0\10\6\3\0\3\6\1\0"+
    "\11\6\1\151\2\6\23\0\1\6\1\0\3\6\2\0"+
    "\10\6\3\0\3\6\1\0\5\6\1\152\6\6\23\0"+
    "\1\6\1\0\3\6\2\0\6\6\1\153\1\6\3\0"+
    "\3\6\1\0\14\6\23\0\1\6\1\0\3\6\2\0"+
    "\1\6\1\154\6\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\1\0\3\6\2\0\1\6\1\155\6\6\3\0"+
    "\3\6\1\0\14\6\23\0\1\6\1\0\3\6\2\0"+
    "\10\6\3\0\3\6\1\0\4\6\1\156\7\6\23\0"+
    "\1\6\16\104\1\157\1\160\45\104\24\0\1\161\43\0"+
    "\1\106\5\0\3\106\5\0\1\106\1\0\1\106\1\0"+
    "\1\106\6\0\1\106\1\0\1\106\27\0\3\6\2\0"+
    "\7\6\1\162\3\0\3\6\1\0\14\6\23\0\1\6"+
    "\1\0\3\6\2\0\10\6\3\0\3\6\1\0\4\6"+
    "\1\163\7\6\23\0\1\6\1\0\3\6\2\0\1\164"+
    "\7\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\6\6\1\165\1\6\3\0\3\6\1\0"+
    "\14\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\10\6\1\166\3\6\23\0\1\6\1\0"+
    "\3\6\2\0\10\6\3\0\3\6\1\0\6\6\1\167"+
    "\5\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\3\6\1\170\10\6\23\0\1\6\1\0"+
    "\3\6\2\0\10\6\3\0\3\6\1\0\4\6\1\171"+
    "\7\6\23\0\1\6\1\0\3\6\2\0\4\6\1\172"+
    "\3\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\7\6\1\173\3\0\3\6\1\0\14\6"+
    "\23\0\1\6\1\0\3\6\2\0\1\6\1\174\6\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\6\0\1\175"+
    "\64\0\1\176\65\0\1\177\64\0\1\200\56\0\3\6"+
    "\2\0\3\6\1\201\4\6\3\0\3\6\1\0\14\6"+
    "\23\0\1\6\1\0\3\6\2\0\3\6\1\202\4\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\1\0\3\6"+
    "\2\0\10\6\3\0\3\6\1\0\5\6\1\203\6\6"+
    "\23\0\1\6\1\0\3\6\2\0\2\6\1\204\5\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\1\0\3\6"+
    "\2\0\10\6\3\0\3\6\1\0\11\6\1\205\2\6"+
    "\23\0\1\6\1\0\3\6\2\0\3\6\1\206\4\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\1\0\3\6"+
    "\2\0\10\6\3\0\3\6\1\0\1\207\13\6\23\0"+
    "\1\6\1\0\3\6\2\0\7\6\1\210\3\0\3\6"+
    "\1\0\14\6\23\0\1\6\1\0\3\6\2\0\5\6"+
    "\1\211\2\6\3\0\3\6\1\0\14\6\23\0\1\6"+
    "\1\0\3\6\2\0\2\6\1\212\5\6\3\0\3\6"+
    "\1\0\4\6\1\213\7\6\23\0\1\6\1\0\3\6"+
    "\2\0\1\214\7\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\17\0\1\160\46\0\3\6\2\0\3\6\1\215"+
    "\4\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\10\6\3\0\3\6\1\0\5\6\1\216"+
    "\6\6\23\0\1\6\1\0\3\6\2\0\3\6\1\217"+
    "\4\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\6\6\1\220\1\6\3\0\3\6\1\0"+
    "\14\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\4\6\1\221\7\6\23\0\1\6\1\0"+
    "\3\6\2\0\6\6\1\222\1\6\3\0\3\6\1\0"+
    "\14\6\23\0\1\6\1\0\3\6\2\0\6\6\1\223"+
    "\1\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\5\6\1\224\2\6\3\0\3\6\1\0"+
    "\14\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\2\6\1\225\11\6\23\0\1\6\10\0"+
    "\1\226\114\0\1\227\37\0\1\230\66\0\1\231\50\0"+
    "\3\6\2\0\1\6\1\232\6\6\3\0\3\6\1\0"+
    "\14\6\23\0\1\6\1\0\3\6\2\0\6\6\1\233"+
    "\1\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\1\234\7\6\3\0\3\6\1\0\14\6"+
    "\23\0\1\6\1\0\3\6\2\0\3\6\1\235\4\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\1\0\3\6"+
    "\2\0\10\6\3\0\3\6\1\0\1\6\1\236\12\6"+
    "\23\0\1\6\1\0\3\6\2\0\10\6\3\0\3\6"+
    "\1\0\1\237\13\6\23\0\1\6\1\0\3\6\2\0"+
    "\10\6\3\0\3\6\1\0\5\6\1\240\6\6\23\0"+
    "\1\6\1\0\3\6\2\0\10\6\3\0\3\6\1\0"+
    "\1\241\13\6\23\0\1\6\1\0\3\6\2\0\1\242"+
    "\7\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\10\6\3\0\3\6\1\0\6\6\1\243"+
    "\5\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\5\6\1\244\6\6\23\0\1\6\1\0"+
    "\3\6\2\0\3\6\1\245\4\6\3\0\3\6\1\0"+
    "\14\6\23\0\1\6\1\0\3\6\2\0\3\6\1\246"+
    "\4\6\3\0\3\6\1\0\14\6\23\0\1\6\1\0"+
    "\3\6\2\0\2\6\1\247\5\6\3\0\3\6\1\0"+
    "\14\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\3\6\1\250\10\6\23\0\1\6\7\0"+
    "\1\251\105\0\1\252\120\0\1\253\31\0\1\254\34\0"+
    "\3\6\2\0\10\6\3\0\3\6\1\0\5\6\1\255"+
    "\6\6\23\0\1\6\1\0\3\6\2\0\10\6\3\0"+
    "\3\6\1\0\5\6\1\256\6\6\23\0\1\6\1\0"+
    "\3\6\2\0\10\6\3\0\3\6\1\0\4\6\1\257"+
    "\7\6\23\0\1\6\1\0\3\6\2\0\1\260\7\6"+
    "\3\0\3\6\1\0\14\6\23\0\1\6\1\0\3\6"+
    "\2\0\10\6\3\0\3\6\1\0\6\6\1\261\5\6"+
    "\23\0\1\6\1\0\3\6\2\0\10\6\3\0\3\6"+
    "\1\0\13\6\1\262\23\0\1\6\1\0\3\6\2\0"+
    "\6\6\1\263\1\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\1\0\3\6\2\0\3\6\1\264\4\6\3\0"+
    "\3\6\1\0\14\6\23\0\1\6\1\0\3\6\2\0"+
    "\5\6\1\265\2\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\1\0\3\6\2\0\6\6\1\266\1\6\3\0"+
    "\3\6\1\0\14\6\23\0\1\6\1\0\3\6\2\0"+
    "\7\6\1\267\3\0\3\6\1\0\14\6\23\0\1\6"+
    "\32\0\1\270\41\0\1\271\105\0\1\272\35\0\3\6"+
    "\2\0\10\6\3\0\3\6\1\0\3\6\1\273\10\6"+
    "\23\0\1\6\1\0\3\6\2\0\10\6\3\0\3\6"+
    "\1\0\5\6\1\274\6\6\23\0\1\6\1\0\3\6"+
    "\2\0\1\6\1\275\6\6\3\0\3\6\1\0\14\6"+
    "\23\0\1\6\1\0\3\6\2\0\10\6\3\0\3\6"+
    "\1\0\5\6\1\276\6\6\23\0\1\6\1\0\3\6"+
    "\2\0\1\277\7\6\3\0\3\6\1\0\14\6\23\0"+
    "\1\6\1\0\3\6\2\0\3\6\1\300\4\6\3\0"+
    "\3\6\1\0\14\6\23\0\1\6\32\0\1\301\33\0"+
    "\3\6\2\0\10\6\3\0\3\6\1\0\5\6\1\302"+
    "\6\6\23\0\1\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7102];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\3\1\1\11\10\1\1\11\11\1\12\11"+
    "\7\1\2\11\2\1\2\11\4\1\2\0\34\1\11\11"+
    "\4\0\1\11\15\1\2\11\13\1\4\0\25\1\4\0"+
    "\17\1\2\0\1\11\1\0\13\1\2\11\1\0\6\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
private String annotation_buffer = "";
private String annotation_type = "";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  ScannerExpr(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2850) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	System.out.println(yytext()); return new Symbol(Terminals.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            } 
            // fall through
          case 70: break;
          case 2: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_IDENTIFIER, yyline, yycolumn, new String(yytext()) );
            } 
            // fall through
          case 71: break;
          case 3: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LIT_INTEGER, yyline, yycolumn, new Integer(yytext()) );
            } 
            // fall through
          case 72: break;
          case 4: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_SEMIC, yyline, yycolumn);
            } 
            // fall through
          case 73: break;
          case 5: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_DIV, yyline, yycolumn);
            } 
            // fall through
          case 74: break;
          case 6: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_TIMES, yyline, yycolumn);
            } 
            // fall through
          case 75: break;
          case 7: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_PLUS, yyline, yycolumn);
            } 
            // fall through
          case 76: break;
          case 8: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_MINUS, yyline, yycolumn);
            } 
            // fall through
          case 77: break;
          case 9: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LPAR, yyline, yycolumn);
            } 
            // fall through
          case 78: break;
          case 10: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_RPAR, yyline, yycolumn);
            } 
            // fall through
          case 79: break;
          case 11: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LBRACKET, yyline, yycolumn);
            } 
            // fall through
          case 80: break;
          case 12: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_RBRACKET, yyline, yycolumn);
            } 
            // fall through
          case 81: break;
          case 13: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LBRACE, yyline, yycolumn);
            } 
            // fall through
          case 82: break;
          case 14: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_RBRACE, yyline, yycolumn);
            } 
            // fall through
          case 83: break;
          case 15: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_COMMA, yyline, yycolumn);
            } 
            // fall through
          case 84: break;
          case 16: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_COLON, yyline, yycolumn);
            } 
            // fall through
          case 85: break;
          case 17: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LT, yyline, yycolumn);
            } 
            // fall through
          case 86: break;
          case 18: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_AFF, yyline, yycolumn);
            } 
            // fall through
          case 87: break;
          case 19: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_GT, yyline, yycolumn);
            } 
            // fall through
          case 88: break;
          case 20: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_NOT, yyline, yycolumn);
            } 
            // fall through
          case 89: break;
          case 21: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_CIRC, yyline, yycolumn);
            } 
            // fall through
          case 90: break;
          case 22: 
            { System.out.print(yytext());
            } 
            // fall through
          case 91: break;
          case 23: 
            { yybegin(ANNOTATION);
            } 
            // fall through
          case 92: break;
          case 24: 
            { System.out.print("-> " + annotation_type + ": " + annotation_buffer); annotation_buffer = ""; yybegin(COMMENT_DOC);
            } 
            // fall through
          case 93: break;
          case 25: 
            { System.out.print("*** LineComment: " + yytext());
            } 
            // fall through
          case 94: break;
          case 26: 
            { System.out.println("*** Multiple Lines Comment:"); yybegin(COMMENT);
            } 
            // fall through
          case 95: break;
          case 27: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LIT_INTEGER, yyline, yycolumn, new Integer(
																																	Integer.decode(yytext())
																																		)
																																	);
            } 
            // fall through
          case 96: break;
          case 28: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_OF, yyline, yycolumn);
            } 
            // fall through
          case 97: break;
          case 29: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_IF, yyline, yycolumn);
            } 
            // fall through
          case 98: break;
          case 30: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_DO, yyline, yycolumn);
            } 
            // fall through
          case 99: break;
          case 31: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_DOTDOT, yyline, yycolumn);
            } 
            // fall through
          case 100: break;
          case 32: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LE, yyline, yycolumn);
            } 
            // fall through
          case 101: break;
          case 33: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_EQ, yyline, yycolumn);
            } 
            // fall through
          case 102: break;
          case 34: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_GE, yyline, yycolumn);
            } 
            // fall through
          case 103: break;
          case 35: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_NE, yyline, yycolumn);
            } 
            // fall through
          case 104: break;
          case 36: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_OR, yyline, yycolumn);
            } 
            // fall through
          case 105: break;
          case 37: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_AND, yyline, yycolumn);
            } 
            // fall through
          case 106: break;
          case 38: 
            { System.out.println("End of the Multiple Lines Comment !"); yybegin(YYINITIAL);
            } 
            // fall through
          case 107: break;
          case 39: 
            { System.out.println("End of the Documentation"); yybegin(YYINITIAL);
            } 
            // fall through
          case 108: break;
          case 40: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_LIT_STRING, yyline, yycolumn, new String(yytext()) );
            } 
            // fall through
          case 109: break;
          case 41: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_END, yyline, yycolumn);
            } 
            // fall through
          case 110: break;
          case 42: 
            { System.out.println("*** Documentation Comment:"); yybegin(COMMENT_DOC);
            } 
            // fall through
          case 111: break;
          case 43: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_NEW, yyline, yycolumn);
            } 
            // fall through
          case 112: break;
          case 44: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_VAR, yyline, yycolumn);
            } 
            // fall through
          case 113: break;
          case 45: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_TRUE, yyline, yycolumn);
            } 
            // fall through
          case 114: break;
          case 46: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_TYPE, yyline, yycolumn);
            } 
            // fall through
          case 115: break;
          case 47: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_THEN, yyline, yycolumn);
            } 
            // fall through
          case 116: break;
          case 48: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_ELSE, yyline, yycolumn);
            } 
            // fall through
          case 117: break;
          case 49: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_CASE, yyline, yycolumn);
            } 
            // fall through
          case 118: break;
          case 50: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_NULL, yyline, yycolumn);
            } 
            // fall through
          case 119: break;
          case 51: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_FALSE, yyline, yycolumn);
            } 
            // fall through
          case 120: break;
          case 52: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_ARRAY, yyline, yycolumn);
            } 
            // fall through
          case 121: break;
          case 53: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_BEGIN, yyline, yycolumn);
            } 
            // fall through
          case 122: break;
          case 54: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_WHILE, yyline, yycolumn);
            } 
            // fall through
          case 123: break;
          case 55: 
            { annotation_type = "param";
            } 
            // fall through
          case 124: break;
          case 56: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_RETURN, yyline, yycolumn);
            } 
            // fall through
          case 125: break;
          case 57: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_READLN, yyline, yycolumn);
            } 
            // fall through
          case 126: break;
          case 58: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_STRUCT, yyline, yycolumn);
            } 
            // fall through
          case 127: break;
          case 59: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_STRING, yyline, yycolumn);
            } 
            // fall through
          case 128: break;
          case 60: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_SWITCH, yyline, yycolumn);
            } 
            // fall through
          case 129: break;
          case 61: 
            { annotation_type = "return";
            } 
            // fall through
          case 130: break;
          case 62: 
            { annotation_type = "author";
            } 
            // fall through
          case 131: break;
          case 63: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_PRINTLN, yyline, yycolumn);
            } 
            // fall through
          case 132: break;
          case 64: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_INTEGER, yyline, yycolumn);
            } 
            // fall through
          case 133: break;
          case 65: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_BOOLEAN, yyline, yycolumn);
            } 
            // fall through
          case 134: break;
          case 66: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_DEFAULT, yyline, yycolumn);
            } 
            // fall through
          case 135: break;
          case 67: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_DISPOSE, yyline, yycolumn);
            } 
            // fall through
          case 136: break;
          case 68: 
            { annotation_type = "version";
            } 
            // fall through
          case 137: break;
          case 69: 
            { System.out.println("*** " + yytext()); return new Symbol(Terminals.TOKEN_FUNCTION, yyline, yycolumn);
            } 
            // fall through
          case 138: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
